# Generated by Django 2.2.6 on 2019-10-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20191023_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
